ignoreFiles:
  - "**/*.js"
  - "**/*.ts"
rules:
  selector-type-no-unknown: null
  declaration-empty-line-before: null
  no-descending-specificity: null
  selector-pseudo-class-no-unknown: null
  color-function-notation: legacy
  alpha-value-notation: number
